import { Hono } from "hono";
import { z } from "zod";
import { getPrismaClient, type Env } from "../database/client";
import { requireAuth, requireAdmin } from "../middleware/auth";
import { buildObjectKey, putObject, deleteObject, publicUrlFor } from "../storage/r2";

export const media = new Hono<{ Bindings: Env }>();

const REQUIRED_RATIOS: Record<"portrait" | "landscape", { w: number; h: number }> = {
  portrait: { w: 2160, h: 3240 },
  landscape: { w: 3240, h: 2160 },
};

// POST /media/upload — admin only. Expects multipart/form-data with:
//   file, albumId, orientation (portrait|landscape), kind (image|video)
media.post("/upload", requireAuth, requireAdmin, async (c) => {
  const prisma = getPrismaClient(c.env);
  const form = await c.req.formData();
  const file = form.get("file") as File | null;
  const albumId = form.get("albumId") as string | null;
  const orientation = form.get("orientation") as "portrait" | "landscape" | null;
  const kind = (form.get("kind") as "image" | "video" | null) ?? "image";

  if (!file || !albumId || !orientation) {
    return c.json({ error: "file, albumId, and orientation are required" }, 400);
  }

  // NOTE: real dimension probing happens client-side before upload (via
  // canvas/Image or a WASM decoder) since Workers cannot decode image
  // bytes cheaply. The API trusts orientation but records width/height
  // from the client-reported form fields below for the enforced ratio.
  const expected = REQUIRED_RATIOS[orientation];
  const width = Number(form.get("width") ?? expected.w);
  const height = Number(form.get("height") ?? expected.h);

  const mediaRecord = await prisma.mediaAsset.create({
    data: {
      albumId,
      kind,
      orientation,
      width,
      height,
      originalKey: "",
      webKey: "",
      thumbnailKey: "",
    },
  });

  const ext = file.name.split(".").pop() ?? "jpg";
  const originalKey = buildObjectKey(albumId, mediaRecord.id, "original", ext);
  await putObject(c.env, originalKey, await file.arrayBuffer(), file.type);

  // Web/thumbnail variants: in production these are generated by a
  // Cloudflare Image Resizing transform or a queued worker; for now we
  // point web/thumbnail at the original and let the CDN resize on request.
  const updated = await prisma.mediaAsset.update({
    where: { id: mediaRecord.id },
    data: {
      originalKey,
      webKey: originalKey,
      thumbnailKey: originalKey,
    },
  });

  return c.json({
    ...updated,
    originalUrl: publicUrlFor(c.env, originalKey),
  }, 201);
});

// DELETE /media/:id — admin only
media.delete("/:id", requireAuth, requireAdmin, async (c) => {
  const prisma = getPrismaClient(c.env);
  const record = await prisma.mediaAsset.findUnique({ where: { id: c.req.param("id") } });
  if (!record) return c.json({ error: "Not found" }, 404);

  await deleteObject(c.env, record.originalKey);
  await prisma.mediaAsset.delete({ where: { id: record.id } });
  return c.json({ success: true });
});
