// Ready-made professional starting points for CMS > Email Designer. Picking one copies its
// blocks into a NEW template -- everything stays fully editable. Brand colours match the site.
// Images are left for Naveed to fill with his own work (Media Library URL) so no stock photos
// are ever sent by accident; image blocks with no URL simply don't render.

const DARK = "#170F28", PURPLE = "#8B5CF6", GOLD = "#C9A96E", INK = "#140D21";
const SITE = "https://bynaveedanjum.com";
const brandBand = (sub = "PHOTOGRAPHY · CINEMATOGRAPHY") => [
  { type: "logo", src: "", width: 150, align: "center", bg: DARK },
  { type: "heading", text: "NAVEED ANJUM", align: "center", color: "#ffffff", size: 22, font: "playfair", bg: DARK, padY: 26, bold: true },
  { type: "text", html: sub, align: "center", color: "#A892C6", size: 11, bg: DARK, padY: 0 },
  { type: "spacer", height: 22, bg: DARK },
];
const footer = [
  { type: "social", instagram: "https://instagram.com/", youtube: "", website: SITE, whatsapp: "" },
  { type: "footer", align: "center", text: "Naveed Anjum · Dubai, UAE\nYou're receiving this because you're a valued contact of Naveed Anjum." },
];

export type StarterTemplate = { key: string; name: string; subject: string; description: string; blocks: any[] };

export const EMAIL_STARTERS: StarterTemplate[] = [
  {
    key: "welcome", name: "Welcome / Introduction", subject: "Lovely to meet you, {{first_name}}",
    description: "Warm first email after meeting a new contact.",
    blocks: [
      { type: "settings", bodyBg: "#f4f1f9", cardBg: "#ffffff", font: "lato", headingFont: "playfair", accent: PURPLE, headingColor: INK, textColor: "#3a3245", radius: 12, preheader: "Thank you for connecting — here's a little about my work." },
      ...brandBand(),
      { type: "heading", text: "Hello {{first_name}},", size: 26 },
      { type: "text", html: "It was a pleasure connecting with you. I'm Naveed — a Dubai-based photographer and cinematographer with over 20 years of experience creating premium visuals for brands, events and people.\n\nWhenever you need images or films that feel as good as your brand looks, I'd love to help." },
      { type: "image", src: "", alt: "Recent work" },
      { type: "button", text: "View My Portfolio", href: SITE },
      { type: "divider" },
      ...footer,
    ],
  },
  {
    key: "newsletter", name: "Newsletter / Latest Work", subject: "New work from the studio",
    description: "Share recent projects with a short story each.",
    blocks: [
      { type: "settings", bodyBg: "#efeaf6", cardBg: "#ffffff", font: "lato", headingFont: "playfair", accent: PURPLE, radius: 10, preheader: "A few favourite projects from this month." },
      ...brandBand("STUDIO NEWS"),
      { type: "heading", text: "This month at the studio", align: "center", size: 28 },
      { type: "text", html: "Hi {{first_name}}, here are a few projects I'm proud of — from luxury real estate to corporate events across the UAE.", align: "center" },
      { type: "image", src: "", alt: "Project one" },
      { type: "heading", text: "Project title", size: 20 },
      { type: "text", html: "One or two lines about the client, the idea and the result." },
      { type: "button", text: "See the full project", href: SITE, align: "left" },
      { type: "divider" },
      { type: "image", src: "", alt: "Project two" },
      { type: "heading", text: "Another project", size: 20 },
      { type: "text", html: "A short description of the shoot and what made it special." },
      { type: "button", text: "Watch the film", href: SITE, align: "left" },
      { type: "spacer", height: 12 },
      ...footer,
    ],
  },
  {
    key: "offer", name: "Special Offer / Promotion", subject: "An exclusive offer for {{company}}",
    description: "Bold promotion with a clear call to action.",
    blocks: [
      { type: "settings", bodyBg: "#120b20", cardBg: "#1d1430", font: "montserrat", headingFont: "montserrat", accent: GOLD, headingColor: "#ffffff", textColor: "#d9d0ea", radius: 14, preheader: "A limited-time package, reserved for valued clients." },
      { type: "logo", src: "", width: 140, align: "center" },
      { type: "text", html: "LIMITED TIME", align: "center", color: GOLD, size: 12, bold: true, padY: 24 },
      { type: "heading", text: "20% off your next shoot", align: "center", size: 34, bold: true },
      { type: "text", html: "Book any photography or video package before the end of the month and receive 20% off — plus a complimentary edited highlight reel.", align: "center" },
      { type: "image", src: "", alt: "Offer" },
      { type: "button", text: "Claim the Offer", href: SITE, btnTextColor: INK, size: 15 },
      { type: "text", html: "Offer valid for new bookings only. Cannot be combined with other offers.", align: "center", size: 11, color: "#8f84a6" },
      { type: "divider", lineColor: "#33264d" },
      ...footer.map((b: any) => (b.type === "footer" ? { ...b, color: "#8f84a6" } : b)),
    ],
  },
  {
    key: "event", name: "Event Invitation", subject: "You're invited, {{first_name}}",
    description: "Invite contacts to an exhibition, launch or open studio.",
    blocks: [
      { type: "settings", bodyBg: "#f7f3ec", cardBg: "#ffffff", font: "raleway", headingFont: "cormorant", accent: DARK, headingColor: INK, textColor: "#4a4256", radius: 4, preheader: "Join us — details inside." },
      { type: "logo", src: "", width: 140, align: "center" },
      { type: "text", html: "YOU ARE INVITED", align: "center", color: GOLD, size: 12, bold: true, padY: 28 },
      { type: "heading", text: "Event name", align: "center", size: 36 },
      { type: "image", src: "", alt: "Event" },
      { type: "text", html: "<b>Date:</b> Thursday, 1 January · 7:00 PM\n<b>Venue:</b> Dubai, UAE", align: "center", size: 15 },
      { type: "text", html: "An evening of photography, film and conversation. I'd be honoured to have you there.", align: "center" },
      { type: "button", text: "RSVP Now", href: "mailto:?subject=RSVP", radius: 0 },
      { type: "divider" },
      ...footer,
    ],
  },
  {
    key: "thanks", name: "Thank You / After the Shoot", subject: "Thank you, {{first_name}} — your photos are ready",
    description: "Follow-up after a project, with delivery link and review ask.",
    blocks: [
      { type: "settings", bodyBg: "#f4f1f9", cardBg: "#ffffff", font: "helvetica", headingFont: "playfair", accent: PURPLE, radius: 12, preheader: "Your gallery is ready to download." },
      ...brandBand(),
      { type: "heading", text: "Thank you, {{first_name}}!", align: "center", size: 28 },
      { type: "text", html: "It was a real pleasure working with you and the {{company}} team. Your final gallery is ready — click below to view and download.", align: "center" },
      { type: "button", text: "Open Your Gallery", href: SITE },
      { type: "divider" },
      { type: "text", html: "If you enjoyed the experience, a short review would mean the world to me.", align: "center", size: 13 },
      { type: "button", text: "Leave a Review", href: SITE, btnColor: "#ffffff", btnTextColor: PURPLE },
      ...footer,
    ],
  },
  // ── Client-journey emails (research: the standard photographer workflow is
  // enquiry → quote → booking → pre-shoot → delivery → review → re-engage) ──
  {
    key: "inquiry", name: "Enquiry Reply", subject: "Thank you for your enquiry, {{first_name}}",
    description: "Fast, warm first reply to a new enquiry — moves them to a call.",
    blocks: [
      { type: "settings", bodyBg: "#f4f1f9", cardBg: "#ffffff", font: "lato", headingFont: "playfair", accent: PURPLE, radius: 12, preheader: "Thank you for reaching out — here's what happens next." },
      ...brandBand(),
      { type: "heading", text: "Thank you for reaching out, {{first_name}}" },
      { type: "text", html: "I've received your enquiry and I'm excited to hear more about your project.\n\nTo give you an accurate proposal, could you share:\n• The date(s) and location\n• What you'd like captured (photo, video, or both)\n• How you'll use the final images or film" },
      { type: "text", html: "Or, if it's easier, let's have a quick 15-minute call — just reply with a time that suits you." },
      { type: "button", text: "Chat on WhatsApp", href: "https://wa.me/", btnColor: "#25D366" },
      { type: "divider" },
      { type: "text", html: "<b>Naveed Anjum</b>\nPhotographer & Cinematographer · Dubai", size: 13, color: "#5d5568" },
      ...footer,
    ],
  },
  {
    key: "proposal", name: "Quote / Proposal", subject: "Your proposal from Naveed Anjum",
    description: "Send a clear quote with what's included and one action button.",
    blocks: [
      { type: "settings", bodyBg: "#efeaf6", cardBg: "#ffffff", font: "helvetica", headingFont: "playfair", accent: DARK, radius: 10, preheader: "Your tailored proposal is ready." },
      ...brandBand("PROPOSAL"),
      { type: "heading", text: "Your proposal, {{first_name}}", size: 26 },
      { type: "text", html: "Thank you for the details. Based on what we discussed for {{company}}, here's what I recommend:" },
      { type: "html", html: "<table width=\"100%\" cellpadding=\"10\" cellspacing=\"0\" style=\"border-collapse:collapse;font-size:14px;\"><tr style=\"background:#f4f1f9;\"><td><b>Package</b></td><td align=\"right\"><b>Premium Coverage</b></td></tr><tr><td>Coverage</td><td align=\"right\">Full day (8 hours)</td></tr><tr style=\"background:#f4f1f9;\"><td>Deliverables</td><td align=\"right\">150+ edited photos · 2-min film</td></tr><tr><td>Delivery</td><td align=\"right\">Within 10 working days</td></tr><tr style=\"background:#140D21;color:#ffffff;\"><td><b>Investment</b></td><td align=\"right\"><b>AED 0,000</b></td></tr></table>" },
      { type: "text", html: "A 50% deposit secures your date. This proposal is valid for 14 days.", size: 13 },
      { type: "button", text: "Accept & Book", href: SITE },
      ...footer,
    ],
  },
  {
    key: "booking", name: "Booking Confirmation", subject: "You're booked! Confirmation for {{first_name}}",
    description: "Confirms date, time, location and next steps after the deposit.",
    blocks: [
      { type: "settings", bodyBg: "#f4f1f9", cardBg: "#ffffff", font: "montserrat", headingFont: "playfair", accent: PURPLE, radius: 12, preheader: "Your date is confirmed — all the details inside." },
      ...brandBand(),
      { type: "text", html: "✓ BOOKING CONFIRMED", align: "center", color: "#2e9e5b", size: 12, bold: true, padY: 20 },
      { type: "heading", text: "See you soon, {{first_name}}!", align: "center", size: 28 },
      { type: "html", html: "<table width=\"100%\" cellpadding=\"12\" cellspacing=\"0\" style=\"border:1px solid #e6e1ee;border-radius:8px;font-size:14px;\"><tr><td style=\"color:#8f84a6;\">Date</td><td align=\"right\"><b>Day, 00 Month 2026</b></td></tr><tr><td style=\"color:#8f84a6;\">Time</td><td align=\"right\"><b>10:00 AM</b></td></tr><tr><td style=\"color:#8f84a6;\">Location</td><td align=\"right\"><b>Venue, Dubai</b></td></tr><tr><td style=\"color:#8f84a6;\">Package</td><td align=\"right\"><b>Package name</b></td></tr></table>" },
      { type: "text", html: "I'll send a short preparation guide a few days before the shoot. If anything changes, just reply to this email.", align: "center" },
      { type: "button", text: "Add to Calendar", href: SITE },
      ...footer,
    ],
  },
  {
    key: "preshoot", name: "Pre-Shoot Guide", subject: "Getting ready for your shoot, {{first_name}}",
    description: "Prep tips sent 2–3 days before — fewer surprises, better results.",
    blocks: [
      { type: "settings", bodyBg: "#f7f3ec", cardBg: "#ffffff", font: "lato", headingFont: "cormorant", accent: DARK, headingColor: INK, radius: 6, preheader: "A few simple tips to get the best results." },
      { type: "logo", src: "", width: 140, align: "center" },
      { type: "heading", text: "Your shoot is almost here", align: "center", size: 32 },
      { type: "text", html: "Hi {{first_name}}, a few simple things will make the day smooth and the results beautiful:", align: "center" },
      { type: "heading", text: "1. What to wear", size: 19 },
      { type: "text", html: "Solid colours and timeless pieces photograph best. Avoid large logos and busy patterns." },
      { type: "heading", text: "2. Timing", size: 19 },
      { type: "text", html: "In Dubai, the best natural light is the first hour after sunrise and the hour before sunset." },
      { type: "heading", text: "3. On the day", size: 19 },
      { type: "text", html: "Please arrive 10 minutes early, and have any permits or venue access arranged." },
      { type: "button", text: "Questions? Message me", href: "https://wa.me/", radius: 0 },
      ...footer,
    ],
  },
  {
    key: "payment", name: "Payment Reminder", subject: "Friendly reminder: invoice for {{company}}",
    description: "Polite, professional balance reminder — keeps the relationship warm.",
    blocks: [
      { type: "settings", bodyBg: "#ffffff", cardBg: "#ffffff", font: "helvetica", headingFont: "helvetica", accent: PURPLE, textColor: "#2b2533", radius: 0, width: 560 },
      { type: "logo", src: "", width: 120, align: "left" },
      { type: "text", html: "Hi {{first_name}},", size: 15, padY: 20 },
      { type: "text", html: "I hope you're well and enjoying the final images. This is a friendly reminder that the balance for invoice <b>#0000</b> (<b>AED 0,000</b>) is due on <b>00 Month</b>.\n\nIf you've already sent it, thank you — please ignore this message.", size: 15 },
      { type: "button", text: "View Invoice", href: SITE, align: "left" },
      { type: "text", html: "Best regards,\n<b>Naveed Anjum</b>", size: 15 },
      { type: "footer", text: "Naveed Anjum · Dubai, UAE" },
    ],
  },
  {
    key: "review", name: "Review Request", subject: "Could you spare 1 minute, {{first_name}}?",
    description: "Ask happy clients for a Google review a week after delivery.",
    blocks: [
      { type: "settings", bodyBg: "#f4f1f9", cardBg: "#ffffff", font: "lato", headingFont: "playfair", accent: PURPLE, radius: 14, preheader: "Your words help other clients find me." },
      ...brandBand(),
      { type: "text", html: "★★★★★", align: "center", color: GOLD, size: 30, padY: 22 },
      { type: "heading", text: "How did we do?", align: "center", size: 28 },
      { type: "text", html: "Hi {{first_name}}, it was a real pleasure working with you. If you're happy with the results, a short Google review would mean a lot — it takes less than a minute and helps others find my work.", align: "center" },
      { type: "button", text: "Leave a Google Review", href: "https://g.page/r/" },
      { type: "text", html: "Thank you for trusting me with your project.", align: "center", size: 13, color: "#8f84a6" },
      ...footer,
    ],
  },
  {
    key: "reengage", name: "Check-in / Re-engagement", subject: "It's been a while, {{first_name}}",
    description: "Reconnect with past clients — great for repeat corporate work.",
    blocks: [
      { type: "settings", bodyBg: "#efeaf6", cardBg: "#ffffff", font: "raleway", headingFont: "playfair", accent: PURPLE, radius: 10, preheader: "New work and a few ideas for {{company}}." },
      ...brandBand(),
      { type: "heading", text: "Hope all is well at {{company}}", size: 26 },
      { type: "text", html: "Hi {{first_name}}, it's been a while since we worked together and I wanted to check in.\n\nI've recently completed some exciting projects — brand films, executive portraits and event coverage — and thought some of it might be useful for your upcoming plans." },
      { type: "image", src: "", alt: "Recent work" },
      { type: "button", text: "See Recent Work", href: SITE },
      { type: "text", html: "If you have anything coming up this quarter, I'd love to help — just reply to this email.", size: 13 },
      ...footer,
    ],
  },
  {
    key: "corporate", name: "Corporate Introduction", subject: "Visual content for {{company}}",
    description: "Professional B2B outreach to marketing teams and agencies.",
    blocks: [
      { type: "settings", bodyBg: "#f2f2f4", cardBg: "#ffffff", font: "helvetica", headingFont: "montserrat", accent: DARK, headingColor: INK, radius: 4, preheader: "Photography & film for brands across the UAE." },
      { type: "logo", src: "", width: 130, align: "left" },
      { type: "text", html: "Dear {{first_name}},", size: 15, padY: 20 },
      { type: "text", html: "I'm Naveed Anjum, a Dubai-based photographer and cinematographer with 20+ years of experience creating premium visual content for brands across the UAE.", size: 15 },
      { type: "heading", text: "How I help teams like {{company}}", size: 18, bold: true },
      { type: "text", html: "• Corporate & executive portraits\n• Brand films and social content\n• Events, launches and conferences\n• Real estate, architecture and hospitality", size: 15 },
      { type: "button", text: "View Portfolio", href: SITE, align: "left", radius: 2 },
      { type: "text", html: "Would you be open to a short call next week?\n\nKind regards,\n<b>Naveed Anjum</b>\nPhotographer & Cinematographer · Dubai", size: 15 },
      { type: "footer", text: "Naveed Anjum · Dubai, UAE · If you'd prefer not to hear from me, just reply \"no thanks\"." },
    ],
  },
  {
    key: "seasonal", name: "Seasonal Greetings (Eid / National Day)", subject: "Warm wishes from Naveed Anjum",
    description: "Elegant greeting card for Eid, UAE National Day or New Year.",
    blocks: [
      { type: "settings", bodyBg: "#0f0a1a", cardBg: "#1a1228", font: "lato", headingFont: "cormorant", accent: GOLD, headingColor: GOLD, textColor: "#e6dff2", radius: 16, preheader: "Wishing you and your loved ones a joyful season." },
      { type: "spacer", height: 30 },
      { type: "text", html: "✦ ✦ ✦", align: "center", color: GOLD, size: 18 },
      { type: "heading", text: "Eid Mubarak", align: "center", size: 44 },
      { type: "text", html: "Dear {{first_name}},\n\nWishing you and your family peace, happiness and prosperity this Eid. Thank you for being part of my journey this year.", align: "center", size: 16 },
      { type: "image", src: "", alt: "Greeting" },
      { type: "text", html: "With warm wishes,\n<b>Naveed Anjum</b>", align: "center", color: GOLD, size: 15 },
      { type: "spacer", height: 20 },
      { type: "footer", text: "Naveed Anjum · Dubai, UAE", align: "center", color: "#7d7290" },
    ],
  },
  {
    key: "minimal", name: "Minimal Personal Letter", subject: "Quick note, {{first_name}}",
    description: "Clean, personal email that looks hand-written — great for follow-ups.",
    blocks: [
      { type: "settings", bodyBg: "#ffffff", cardBg: "#ffffff", font: "georgia", headingFont: "georgia", accent: INK, textColor: "#2b2533", radius: 0, width: 560 },
      { type: "text", html: "Hi {{first_name}},", size: 16, padY: 28 },
      { type: "text", html: "Write your message here — short and personal works best.\n\nBest regards,", size: 16 },
      { type: "text", html: "<b>Naveed Anjum</b>\nPhotographer & Cinematographer · Dubai\n<a href=\"" + SITE + "\">bynaveedanjum.com</a>", size: 14, color: "#5d5568" },
    ],
  },
];
